<?php
/*
 * The eleven statutory holidays in British Columbia.
 *
 * Every one of these is a day somebody is owed money for, so a date that is
 * wrong is a payment that is wrong, and the two ways to get one wrong are
 * both here.
 *
 * The first is arithmetic: "third Monday in February" and "the Monday on or
 * before 24 May" are easy to write and easy to write off by one, and the
 * error only shows in the years where it matters.
 *
 * The second is copying a list from somewhere else. Easter Sunday and Boxing
 * Day are statutory holidays in other provinces and are not in BC, and
 * Truth and Reconciliation is in BC and is not everywhere.
 *
 * Dates below were checked against the calendar, not generated by the code
 * they are testing.
 */
require __DIR__ . '/wp-stubs.php';
define('BFTD_PATH', dirname(__DIR__) . '/');
if (!defined('BFTD_URL')) define('BFTD_URL', '');
if (!defined('DAY_IN_SECONDS')) define('DAY_IN_SECONDS', 86400);

require BFTD_PATH . 'includes/class-bftd-stat-holidays.php';

$fail = 0;
function check($ok, $msg) { global $fail; echo ($ok ? "  ok   " : "FAIL  ") . $msg . "\n"; if (!$ok) $fail++; }
function is($got, $want, $msg) { check($got === $want, $msg . ($got === $want ? '' : " (got " . var_export($got, true) . ", wanted " . var_export($want, true) . ")")); }

/* ---- how many, and which ---- */
$y2026 = BFTD_Stat_Holidays::in_year(2026);
is(count($y2026), 11, 'there are eleven of them in a year');

$names = array_values($y2026);
foreach (array(
  "New Year's Day", 'Family Day', 'Good Friday', 'Victoria Day', 'Canada Day',
  'British Columbia Day', 'Labour Day', 'National Day for Truth and Reconciliation',
  'Thanksgiving Day', 'Remembrance Day', 'Christmas Day',
) as $want) {
  check(in_array($want, $names, true), $want . ' is one of them');
}

/* The ones that are somebody else's statutory holiday and not BC's. */
is(BFTD_Stat_Holidays::name_for('2026-12-26'), '', 'Boxing Day is not a statutory holiday in BC');
is(BFTD_Stat_Holidays::name_for('2026-04-06'), '', 'and neither is Easter Monday');
is(BFTD_Stat_Holidays::name_for('2026-04-05'), '', 'nor Easter Sunday');

/* ---- the fixed ones ---- */
is(BFTD_Stat_Holidays::name_for('2026-01-01'), "New Year's Day", 'the first of January');
is(BFTD_Stat_Holidays::name_for('2026-07-01'), 'Canada Day', 'the first of July');
is(BFTD_Stat_Holidays::name_for('2026-09-30'), 'National Day for Truth and Reconciliation', 'the thirtieth of September');
is(BFTD_Stat_Holidays::name_for('2026-11-11'), 'Remembrance Day', 'the eleventh of November');
is(BFTD_Stat_Holidays::name_for('2026-12-25'), 'Christmas Day', 'the twenty-fifth of December');

/* A fixed holiday on a weekend stays where it fell. Substituting another day
   is something an employer and an employee may AGREE to, and an agreement is
   not something a calendar can know about. */
is(BFTD_Stat_Holidays::name_for('2028-01-01'), "New Year's Day", 'a fixed holiday on a Saturday is still on the Saturday');
is(BFTD_Stat_Holidays::name_for('2028-01-03'), '', 'and is not quietly moved to the Monday');

/* ---- the counted ones ---- */
is(BFTD_Stat_Holidays::name_for('2026-02-16'), 'Family Day', 'the third Monday in February 2026');
is(BFTD_Stat_Holidays::name_for('2027-02-15'), 'Family Day', 'and in 2027');
is(BFTD_Stat_Holidays::name_for('2025-02-17'), 'Family Day', 'and in 2025');

is(BFTD_Stat_Holidays::name_for('2026-08-03'), 'British Columbia Day', 'the first Monday in August 2026');
is(BFTD_Stat_Holidays::name_for('2027-08-02'), 'British Columbia Day', 'and in 2027');

is(BFTD_Stat_Holidays::name_for('2026-09-07'), 'Labour Day', 'the first Monday in September 2026');
is(BFTD_Stat_Holidays::name_for('2027-09-06'), 'Labour Day', 'and in 2027');

is(BFTD_Stat_Holidays::name_for('2026-10-12'), 'Thanksgiving Day', 'the second Monday in October 2026');
is(BFTD_Stat_Holidays::name_for('2027-10-11'), 'Thanksgiving Day', 'and in 2027');

/* A month whose first day IS the weekday being counted, which is the off-by-
   one every nth-weekday routine gets wrong. */
is(BFTD_Stat_Holidays::name_for('2025-09-01'), 'Labour Day', 'Labour Day when the first of the month is itself the Monday');

/* ---- Victoria Day: the Monday on or before 24 May ---- */
is(BFTD_Stat_Holidays::name_for('2026-05-18'), 'Victoria Day', 'Victoria Day 2026');
is(BFTD_Stat_Holidays::name_for('2027-05-24'), 'Victoria Day', 'and 2027, when the 24th is itself a Monday');
is(BFTD_Stat_Holidays::name_for('2025-05-19'), 'Victoria Day', 'and 2025');
is(BFTD_Stat_Holidays::name_for('2028-05-22'), 'Victoria Day', 'and 2028');

/* ---- Good Friday, which is the one that actually moves ---- */
is(BFTD_Stat_Holidays::name_for('2026-04-03'), 'Good Friday', 'Good Friday 2026');
is(BFTD_Stat_Holidays::name_for('2027-03-26'), 'Good Friday', 'and 2027, which is in March');
is(BFTD_Stat_Holidays::name_for('2025-04-18'), 'Good Friday', 'and 2025');
is(BFTD_Stat_Holidays::name_for('2024-03-29'), 'Good Friday', 'and 2024');
is(BFTD_Stat_Holidays::name_for('2030-04-19'), 'Good Friday', 'and 2030');
is(BFTD_Stat_Holidays::name_for('2038-04-23'), 'Good Friday', 'and 2038, which is the latest it gets this century');

/* ---- a range ---- */
$fortnight = BFTD_Stat_Holidays::between('2026-12-16', '2026-12-31');
is($fortnight, array('2026-12-25' => 'Christmas Day'), 'a pay period knows the one holiday in it');
is(BFTD_Stat_Holidays::between('2026-06-01', '2026-06-30'), array(), 'and a month with none in it knows that too');

/* Over the turn of the year, which is where a range built one year at a time
   loses one end or the other. */
$turn = BFTD_Stat_Holidays::between('2026-12-20', '2027-01-05');
is(array_keys($turn), array('2026-12-25', '2027-01-01'), 'a range crossing new year holds both sides of it');

/* ---- in order ---- */
$keys = array_keys($y2026);
$sorted = $keys; sort($sorted);
is($keys, $sorted, 'a year comes out in date order');

exit($fail ? 1 : 0);
